### ISSUE TITLE
pinning guide - what pins to use?

### ISSUE THREAD

**Issue by Knochi** [adafruit/Adafruit_ZeroI2S#3]
Hi,

if someone (me) wants to create a wing with I2S interface it's a bit tricky to figure out the right pins.
From "Learn" I found that 

- Feather M0 is capable of either I2S Data out OR Data in
  - WS (pin0), CLK(pin1)
  - Data In/out (pin9)
- Feather M4 is cabable of I2S Data out AND Data in (simultaneous) 
  - WS (pin0), CLK(pin1)
  - Data in (pin12)
  - Data out (pin11)

From basic example I found pin2 as data in.
> Adafruit_ZeroI2S i2s(0, 1, 9, 2);

And last but not least.. if the MCLK output is supported in the future.. which pin would that be?

**Comment by ladyada** [comment]
yeah there's no 'universal' connectivity for M4/M0 - we tried but could not make it work
M0 does not have MCLK exposed
M4 has MCLK on D0
nRF52840 can use any pins (yay)
ESP32 can also use any pins (we think)
STM32F405 has I2S Pins:
```
    #1/Tx - I2S2 bit_clock pin.
    #6 - I2S2 master clock pin
    #10 - I2S2 word_select pin.
    #11 - I2S2 data pin.
```

**Comment by Knochi** [comment]
> yeah there's no 'universal' connectivity for M4/M0 - we tried but could not make it work
> M0 does not have MCLK exposed
> M4 has MCLK on D0
Oh so i got the M4 wrong.. D0 is MCLK and pin10 is WS(I2SFS0)?

**Comment by ladyada** [comment]
you check the samd51 datasheet to be sure

**Comment by klw1971** [comment]
Hi ladyada,

Love the work - Metro M4 Airlift... very cool!

Now we built a custom board as a simple I2S converter for one of our projects based on Metro M4 / SAMD51.  Unfortunately, I2S is connected using pins PA09 (FS), PA10 (CLK) instead of D9 and D3 respectively.  :-(  D8 (SDO) and D1 (SDI) remain the same.  The board only has the processor, SPI for communications and a digital audio device (microphone and speaker via I2S)... so no QSPI flash and no WiFi.

I found PA09 (FLASH_IO1) and PA10 (FLASH_IO2) in the schematic but I don't know what Adafruit_ZeroI2S is expecting for initialization.

Adafruit_ZeroI2S i2s(9, 3, 8, 1);  // standard configuration
Adafruit_ZeroI2S i2s(?, ?, 8, 1);  // with PA09 (I2SFS) and PA10 (I2SCK)

I tried 18 and 19 as they are labelled in the schematic... I2S starts but I don't get any data.  I also tried PIN_QSPI_IO1 and PIN_QSPI_IO2 but then initialization hangs on pinPeripheral().  I also tried to disable any trace of QSPI Flash in variant.h/cpp.

#define PIN_QSPI_IO1    (44u)
#define PIN_QSPI_IO2    (45u)

Any hints?  Is it actually possible to address those pins?

Thanks!

**Comment by ladyada** [comment]
https://github.com/adafruit/ArduinoCore-samd/blob/master/variants/metro_m4_airlift/variant.h#L198

**Comment by klw1971** [comment]
Ok cool - I just saw I2S flow now... 8000 samples per second. :-)  Thanks!

```
ATDnnn;
184 VDD 0 idleCount 1739844 CPU 19
185 VDD 0 idleCount 1740068 CPU 19
dma_i2s_tx_callback()
dma_i2s_rx_callback()
...
dma_i2s_tx_callback()
dma_i2s_rx_callback()
187 VDD 0 idleCount 1718352 CPU 20
i2sReadTooFast 7966
i2sWriteTooFast 8000
```

**Comment by CanaryEarth** [comment]
The guide is really difficult if you need to use custom pins. The Adafruit MAX98357 has pins labeled **LRC, BCLK, DIN, GAIN, SD, GND, Vin**. The library has pins named **FS_PIN, SCK_PIN, TX_PIN, RX_PIN**. The wiring diagram shows three wires connected (plus power and ground). Those three wires would logically mean you need to connect them to **LRC, BCLK, DIN** but then there is this line of code `Adafruit_ZeroI2S i2s(0, 1, 9, 2);` to make us cry. If you're new like me and just bought this board, it is very confusing to implement.
